# Generated by Django 5.0.4 on 2024-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
