# Generated by Django 5.0.4 on 2024-04-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(default='just chillin', max_length=255),
            preserve_default=False,
        ),
    ]
